In [2]:
import torch

In [3]:
x = torch.linspace(1, 8, steps=8).view(4, 2)
print(x)

area1=(x[:,0]>5.5)&(x[:,1]>5.5)

c=x[:,0]*x[:,1]
area2=c>25

area=area1|area2
print(x[area])

if 0:
# index=torch.max(area,1)[0]
    b=x[area]
# b= x[torch.where((x[:,0]>0) & (x[:,0]<6))]
# print(b)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[5., 6.],
        [7., 8.]])


In [13]:
y = torch.Tensor([1,2,3,4])
val, idx = y.topk(1)
val, idx

(tensor([4.]), tensor([3]))