In [1]:
import torch

In [2]:
y = torch.tensor([[1, 0], [2, 3]])
val, idx = y.max(dim=1, keepdim=True)
print(val)
print(idx)

tensor([[1],
        [3]])
tensor([[0],
        [1]])


In [3]:
idx.view(idx.shape[0])

tensor([0, 1])

In [4]:
# 转成一维向量后，就能使用前面第6节中的“索引方式”了
y[range(y.shape[0]), idx.view(idx.shape[0])]

tensor([1, 3])

In [5]:
def CrossEntropyLoss(O, y):
    '''解决溢出问题的CrossEntropyLoss，集成了softmax和cross_entropy，返回一维Tensor向量'''
    val, idx = O.max(dim=1, keepdim=True)
    O_sub = O - val                 # 减去每行的最大值
    O_exp = torch.exp(O_sub)        # 按元素做exp
    O_exp_sum = O_exp.sum(dim=1)    # 行和，已经压缩成Tensor向量了
    part2 = torch.log(O_exp_sum)    # 取自然对数
    part1 = O_sub[range(O_exp.shape[0]), y] # 类似上面的索引方式
    return - part1 + part2

In [8]:
y = torch.tensor([1, 2, 0])
O = torch.tensor([[1, -float('inf'), 1], [1, 1, 1], [1, 2, 3]])
CrossEntropyLoss(O, y)

tensor([   -inf,  1.0986, -1.5924])