## 数据操作

In [15]:
import torch

### 1.基本

In [16]:
X = torch.arange(12)
X

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
X.numel()

12

从标准正态分布中随机采样

In [18]:
torch.randn((3,4))

tensor([[ 0.2764,  1.4256, -0.5491, -0.8911],
        [-0.8002, -0.6288, -0.0994, -1.0551],
        [-0.7116,  1.3540,  0.7458,  2.1872]])

### 2.运算符
torch中重载了+ - * / **，成为两个相同形状的tensor的按元素运算；

也可以执行其它线性代数运算；

In [19]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [21]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [22]:
X.sum()

tensor(66.)

### 3.广播机制
若运算符shape不等，则无法按元素操作，如下a和b；

此时会将两个矩阵广播成相同维度的矩阵，a复制列，b复制行，再按元素操作

In [23]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [24]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 4.索引和切片
类似numpy

如果我们想为多个元素赋同一个值，只需要如下操作

In [26]:
print(X)
X[0:2, :] = 12
print(X)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


### 5.节省内存
运行一些操作可能会导致为新结果分配内存。 例如，如果我们用Y = X + Y，我们将取消引用Y指向的张量，而是指向新分配的内存处的张量。

In [27]:
before = id(Y)
Y = Y + X
id(Y) == before

False

这是不可取的，内存浪费+有时候会误引用旧的。

torch中执行inplace操作十分简单，只需要加上'[:]'，或使用'Y += X'

In [28]:
before = id(Y)
Y[:] = Y + X
id(Y) == before

True

### 6.转为其它python对象

In [29]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [31]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

注意，其中与numpy.ndarray互转时，.numpy和.from_numpy方法是可以共享内存的，但如果使用torch.tensor(ndarray)由numpy数组生成tensor，就不会共享内存。