## 16.pytorch神经网络基础

### 读写文件

#### 加载和保存张量

In [1]:
import torch
from torch import nn
from torch.nn import functional as F

x = torch.arange(4)
torch.save(x, 'x-file')
x2 = torch.load('x-file')
x2 == x

tensor([True, True, True, True])

#### 存储一个张量列表，然后把它们读回内存

In [2]:
y = torch.zeros(4)
torch.save([x,y], 'x-files')
x2, y2 = torch.load('x-files')
print(x2==x)
print(y2==y)

tensor([True, True, True, True])
tensor([True, True, True, True])


#### 写入或读取从字符串映射到张量的字典

In [4]:
mydict = {'x':x, 'y':y}
torch.save(mydict, 'mydict')
mydict2 = torch.load('mydict')
print(mydict2['x'] == mydict['x'])
print(mydict2['y'] == mydict['y'])

tensor([True, True, True, True])
tensor([True, True, True, True])


#### 加载模型和保存参数

In [5]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)
    def forward(self, X):
        return self.output(F.relu(self.hidden(X)))

net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

   - 不方便把整个模型的模型定义存下来
   - 一般只保存参数，模型另存

In [7]:
torch.save(net.state_dict(), 'mlp.params')
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()
Y_clone = clone(X)
(Y_clone == Y).all()

tensor(True)